
# this file assumes the env variables are already base64 encoded

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-secret-env
type: Opaque
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value }} # $value | b64enc
{{- end -}}
