
name: build pull request
on:
  pull_request:
    branches:
      - master

jobs:
  build-pull-request:
    runs-on: ubuntu-latest
    steps:

    ##
    ## checkout
    ##

    - name: checkout
      uses: actions/checkout@v2

    - name: set up node
      uses: actions/setup-node@v1
      with:
        node-version: 15

    ##
    ## project build
    ##

    - name: npm install and build
      shell: bash
      run: |
        npm install && npm run build
