
name: deploy to stage
on:
  push:
    branches:
    - master

env:
  REGISTRY: ghcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

    ##
    ## checkout and docker setup
    ##

    - name: checkout
      uses: actions/checkout@v2

    - name: set up qemu
      uses: docker/setup-qemu-action@v1

    - name: set up docker buildx
      uses: docker/setup-buildx-action@v1

    - name: login to github container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    ##
    ## project build
    ##

    - name: npm install and build
      shell: bash
      run: |
        npm install && npm run build

    ##
    ## push web image
    ##

    - name: push web image
      uses: docker/build-push-action@v2
      with:
        file: ./web/Dockerfile
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository }}/web:${{ github.sha }}

    # ##
    # ## push images for microservices
    # ##

    # - name: push image - core
    #   uses: docker/build-push-action@v2
    #   with:
    #     file: ./s/Dockerfile
    #     context: .
    #     push: true
    #     tags: chase-moskal/xiome/core:${{ github.sha }}

    # ##
    # ## deploy to stage
    # ##

    # - name: set kubeconfig
    #   uses: azure/k8s-set-context@v1
    #   with:
    #     method: kubeconfig
    #     kubeconfig: ${{ secrets.STAGE_KUBECONFIG }}
    #   id: setcontext

    # - name: helm deployment
    #   shell: bash
    #   env:
    #     GITHASH: ${{ github.sha }}
    #   run: |
    #     helm upgrade metalstage ./metalback \
    #       --atomic \
    #       --wait \
    #       --install \
    #       --namespace metalshop \
    #       --set images.tag=$GITHASH \
    #       -f ./metalback/values-stage.yaml
