
name: deploy to stage
on:
  push:
    branches:
    - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

    ##
    ## checkout and build
    ##

    - name: checkout
      uses: actions/checkout@v2

    - name: npm install and build
      shell: bash
      run: |
        npm install && npm run build

    ##
    ## docker setup
    ##

    - name: login to github pages
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: extract metadata for images
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    ##
    ## push web image
    ##

    - name: push web image
      uses: docker/build-push-action@v2
      with:
        repository: xiome-web
        dockerfile: ./web/Dockerfile
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    ##
    ## push images for microservices
    ##

    - name: push server image
      uses: docker/build-push-action@v2
      with:
        repository: xiome-server
        dockerfile: ./s/Dockerfile
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    # ##
    # ## deploy to stage
    # ##

    # - name: set kubeconfig
    #   uses: azure/k8s-set-context@v1
    #   with:
    #     method: kubeconfig
    #     kubeconfig: ${{ secrets.STAGE_KUBECONFIG }}
    #   id: setcontext

    # - name: helm deployment
    #   shell: bash
    #   env:
    #     GITHASH: ${{ github.sha }}
    #   run: |
    #     helm upgrade metalstage ./metalback \
    #       --atomic \
    #       --wait \
    #       --install \
    #       --namespace metalshop \
    #       --set images.tag=$GITHASH \
    #       -f ./metalback/values-stage.yaml
