
name: deploy to stage
on:
  push:
    branches:
    - master

env:
  REGISTRY: ghcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

    ##
    ## checkout and docker setup
    ##

    - name: checkout
      uses: actions/checkout@v2

    - name: set up qemu
      uses: docker/setup-qemu-action@v1

    - name: set up docker buildx
      uses: docker/setup-buildx-action@v1

    - name: login to github container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    ##
    ## project build
    ##

    - name: npm install and build
      shell: bash
      run: |
        npm install && npm run build

    ##
    ## push images
    ##

    - name: push image - web
      uses: docker/build-push-action@v2
      with:
        file: ./web/Dockerfile
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository }}/web:${{ github.sha }}

    - name: push image - server
      uses: docker/build-push-action@v2
      with:
        file: ./s/Dockerfile
        context: .
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository }}/server:${{ github.sha }}

    ##
    ## deploy to stage
    ##

    - name: set kubeconfig
      uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.STAGE_KUBECONFIG }}
      id: setcontext

    - name: helm deployment
      shell: bash
      env:
        GITHASH: ${{ github.sha }}
        XIOME_CONFIG: ${{ secrets.STAGE_XIOME_CONFIG }}
        XIOME_PUBLIC_KEY: ${{ secrets.STAGE_XIOME_PUBLIC_KEY }}
        XIOME_PRIVATE_KEY: ${{ secrets.STAGE_XIOME_PRIVATE_KEY }}
      run: |
        helm upgrade xiome ./helmchart \
          --atomic \
          --wait \
          --install \
          --namespace xiome \
          --set images.tag=$GITHASH \
          --set env.XIOME_CONFIG="$XIOME_CONFIG" \
          --set env.XIOME_PUBLIC_KEY="$XIOME_PUBLIC_KEY" \
          --set env.XIOME_PRIVATE_KEY="$XIOME_PRIVATE_KEY" \
          -f ./helmchart/values-stage.yaml
